apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketIssuance
  labels:
    app: ticketIssuance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketIssuance
  template:
    metadata:
      labels:
        app: ticketIssuance
    spec:
      containers:
        - name: ticketIssuance
          image: username/ticketIssuance:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5